### ISSUE TITLE
Upgrade to Larvel 5.1 and rebase code back in

### ISSUE THREAD

**Issue by ericdowell** [monkblog/monkblog-php#3]
Delete all code from previous development. Instead have a fresh copy of the current stable laravel 5.1 and slowly move code back in. Also move code to monkcore-php as needed.

**Comment by BenOvermyer** [comment]
You don't mean to completely annihilate the original app, right? Just follow the recommended procedure for upgrading?

Attendant concern: more than just "let's upgrade," we should have a conversation about new features in 5/5.1 to take advantage of.

**Comment by ericdowell** [comment]
I wanted to get a fresh look at setting up the testing, code coverage and so on. I will be slowly adding parts of code back in and some of it will probably go in the other repo https://github.com/monkblog/monkcore-php. That's where a lot of helpful logic will live, Admin controllers, Admin Blade Templates (namespaced), helpers, and I think even the models (still have to try that out). 

Once the repo gets back to 'feature complete' I was thinking of taking the same approach as Laravel and creating a branch called '2.0', keeping master and deleting the others.

**Comment by BenOvermyer** [comment]
That's an interesting approach. Go for it, we'll see how it turns out!
