### ISSUE TITLE
Upgrade to Laravel 8

### ISSUE THREAD

**Issue by BenOvermyer** [monkblog/monkblog-php#45]
Upgrade the project to Laravel 8.

**Comment by apoorvpal01** [comment]
I can take this up. Please assign it to me.

**Comment by apoorvpal01** [comment]
@BenOvermyer may I also update the dependencies for PHP 8? Also, monkblog/theme-manager seems to be compatible with only Laravel 5.1. Could that be updated, please?

**Comment by BenOvermyer** [comment]
Yes, you can update for PHP 8.

I'll work on getting theme-manager to work with Laravel 8.

**Comment by BenOvermyer** [comment]
@apoorvpal01 After looking at the theme-manager code, and digging deeper into this project's code, I think it's better to just let this project stay dead.

Sorry for wasting your time!
